// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dkyfqcmjiokhnsunginw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRreWZxY21qaW9raG5zdW5naW53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUyNDM2MjcsImV4cCI6MjA1MDgxOTYyN30.w3OKAEK1lRm25KMwPMoLO78pJqhdkkGbJFvHYzt6G5E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);